
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8190 	#server\u7AEF\u5730\u5740
        username: admin
        password: password
        instance:
          service-base-url: http://localhost:8188
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: '*'

# info\u4FE1\u606F\u4F1A\u663E\u793A\u5230SBA\u7684server\u7AEF\uFF0C\u8FD9\u91CC\u53D6\u7684\u662Fmaven\u4E2D\u7684\u6570\u636E
info:
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@
server:
  port: 8188
